# docker-compose.yml

version: '3'

networks:
  app-tier:
      driver: bridge

services:
  mysqldb:
    image: mysql:5.7
    platform: linux/amd64
    restart: unless-stopped
    networks:
      - app-tier
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ac_twitter_workspace
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    networks:
      - app-tier

volumes: 
  db: